### ISSUE TITLE
Updated Tutorial repository with version 0.5.0

### ISSUE THREAD

**Issue by andresmasegosa** [amidst/tutorial#1]
- Update the code at the repository with version 0.5.0. 
- Integrate this repository on travis-ci.
- Include a suit of tests to verify that all the java classes runs properly. This could be done by simply invoking the main method of each class. 
- Add also here the code in the module examples, so people have in one place of the code needed to understand AMIDST. Add also the corresponding tests to verify everything works properly.

**Comment by rcabanasdepaz** [comment]
finished but for the last point. A problem found with DataFlinkLoader.loadDataFromFile

**Comment by andresmasegosa** [comment]
This test has been fixed.
