### ISSUE TITLE
Minor query: InferenceAlgorithmForDBN.getPredictivePosterior()

### ISSUE THREAD

**Issue by gunjanthesystem** [amidst/tutorial#2]
Hi,

Thanks for the useful library. I am trying to use it for my project, hence going through the tutorials to get my head around it.

file: https://github.com/amidst/tutorial/blob/master/src/main/java/eu/amidst/tutorial/usingAmidst/examples/DynamicModelInference.java

Does  _infer.getPredictivePosterior(varTarget, 2)_ (line 50) means for _t=t+5_ (line 52)  ? or is there a typo there? 

Thanks,

(ps: I am trying to use it for predicting the next symbol in a timestamped sequence of symbols)

**Comment by andresmasegosa** [comment]
HI @gunjanthesystem , 

Yes It's a typo! Thanks for the feedback. 

Andres
